### ISSUE TITLE
Order in == matters

### ISSUE THREAD

**Issue by ilevd** [HaxeFoundation/hxjava#39]
I have such code:

```haxe
class HelloWorld {
    static public function main() {
      var v:V = new V();
      trace(v.equiv(10));
    }
}

class V {
    public function new(){}

    public function equiv(v:Any):Bool {
      if (v == this) {
        return true;
      }
      return false;
    }
}
```
compiling with: `haxe -main HelloWorld  --java java/Main`

And get error:

```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class haxe.root.V (java.lang.Integer is in module java.base of loader 'bootstrap'; haxe.root.V is in unnamed module of loader 'app')
  at haxe.root.V.equiv(Unknown Source)
  at haxe.root.HelloWorld.main(Unknown Source)
  at haxe.root.HelloWorld.main(Unknown Source)
```

If I change the order in `if`  to `this == v `it works without error. So the order matters and that is strange. 

Expected result - it works without Exception in both cases.

**Comment by ilevd** [comment]
Found in https://haxe.org/manual/type-system-unification.html:

> Operator unification: Certain operators expect certain types which the given types are unified against. For instance, the expression a && b unifies both a and b with Bool and the expression a == b unifies a with b.

So that's apparently cause the error, but, well, that's not that obvious if you don't know about it.
